.eslintignore
app/extend/context.js
package.json
test/fixtures/apps/upload-one-file/app/controller/async.js
test/fixtures/apps/upload-one-file/app/router.js
test/multipart.test.js

feat: getFileStream return promise

---

LICENSE
package.json
test/multipart.test.js

deps: upgrade all dev deps

---

app.js
test/fixtures/apps/multipart/config/config.default.js
test/multipart.test.js

- `whitelist`
Add upper case extname support, like `.JPG`, `.PNG`, etc.

feat: Add upper case extname support

---

package.json
test/multipart.test.js

test: fix wrong result introduced by onerror

---

app.js
app/extend/context.js
package.json
test/fixtures/apps/upload-limit/app/router.js
test/fixtures/apps/upload-limit/config/config.default.js
test/fixtures/apps/whitelist-function/config/config.default.js
test/multipart.test.js

test: improve code coverage

---

README.md

docs: add more example

---

README.md

https://github.com/eggjs/egg-multipart/pull/19/files#r221422635

chore: fix egg docs build

---

.gitignore
README.md
app/extend/context.js
app/middleware/multipart.js
test/file-mode.test.js
test/fixtures/apps/file-mode/app/controller/upload.js

feat: export ctx.cleanupRequestFiles to improve cleanup more easy

---

.travis.yml
README.md
app.js
app/extend/context.js
app/middleware/multipart.js
app/schedule/clean_tmpdir.js
azure-pipelines.template.yml
package.json
test/file-mode.test.js
test/fixtures/apps/fileModeMatch/app/controller/upload.js
test/fixtures/apps/fileModeMatch/app/router.js
test/fixtures/apps/fileModeMatch/app/views/home.html
test/fixtures/apps/fileModeMatch/config/config.default.js
test/fixtures/apps/fileModeMatch/config/config.unittest.js
test/fixtures/apps/fileModeMatch/package.json
test/fixtures/apps/wrong-fileModeMatch-value/config/config.default.js
test/fixtures/apps/wrong-fileModeMatch-value/package.json
test/fixtures/apps/wrong-fileModeMatch/config/config.default.js
test/fixtures/apps/wrong-fileModeMatch/package.json
test/multipart.test.js
test/stream-mode-with-filematch.test.js
test/wrong-mode.test.js

using `options.fileModeMatch` to match the requests.

feat: support file mode on default stream mode

---

config/config.default.js
index.d.ts

https://github.com/eggjs/egg-multipart/pull/30

chore: add typings and jsdocs

---

app/middleware/multipart.js
test/file-mode.test.js

fix: keep same metas as file stream on file mode

---

README.md
app/extend/context.js
app/middleware/multipart.js
app/schedule/clean_tmpdir.js
index.d.ts
test/fixtures/apps/fileModeMatch/app/controller/save.js
test/fixtures/apps/fileModeMatch/app/router.js
test/multipart.test.js
test/stream-mode-with-filematch.test.js

allow controller use file mode in dynamic logic

feat: export saveRequestFiles to context

---

index.d.ts

fix: declaration file

---

.travis.yml
app/extend/context.js
test/dynamic-option.test.js
test/file-mode.test.js
test/fixtures/apps/dynamic-option/app/controller/upload.js
test/fixtures/apps/dynamic-option/app/router.js
test/fixtures/apps/dynamic-option/app/views/home.html
test/fixtures/apps/dynamic-option/config/config.default.js
test/fixtures/apps/dynamic-option/config/config.unittest.js
test/fixtures/apps/dynamic-option/package.json

feat: saveRequestFiles support options

---

app/extend/context.js
test/multipart.test.js

fix: add more error message

---

README.md

ctx.cleanupRequestFiles会删除掉所有的临时文件，使后面的循环发生错误

docs: fix error handler example

---

app/extend/context.js
test/fixtures/apps/upload-one-file/app/router.js
test/multipart.test.js

fix: incorrect file size limit

---

.travis.yml
README.md
app/extend/context.js
config/config.default.js
test/file-mode.test.js

feat: allow array fileds in file mode

---

app/extend/context.js
test/file-mode.test.js

fix: fix array filed value

---

README.md
app/schedule/clean_tmpdir.js
config/config.default.js

Deleting the temporary folder is optional
You can turn off the scheduled task of deleting the temporary folder

feat: Turning off the scheduled task of deleting the temporary directory is optional

---

package.json

fix install warning(https://github.com/eggjs/egg/issues/4695),  upgrade uuid to the latest version(8.3.2,  Node>=8, 10, 12, 14)

deps: upgrade uuid to the latest version for install warning

---

index.d.ts

Add field 'autoFields' type
---
Checklist

fix: add autoFields dts

---

.github/workflows/nodejs.yml
.gitignore
app/extend/context.js
app/schedule/clean_tmpdir.js
config/config.default.js
package.json
test/dynamic-option.test.js
test/file-mode-limit-filesize-per-request.test.js
test/file-mode.test.js
test/fixtures/apps/upload-limit/app/router.js
test/fixtures/apps/upload-one-file/app/controller/async.js
test/fixtures/apps/upload-one-file/app/router.js
test/multipart.test.js
test/stream-mode-with-filematch-glob.test.js
test/stream-mode-with-filematch.test.js
test/ts.test.js

- co-busbox 1.x -> 2.x  (fileSize and fieldSize changed from `<=10mb` to `<10mb`)
- node 14.x+
- simplify deps, remove `mz`/`mz-modules`/`moment`

BREAKING_CHANGE: update deps co-busbox && node>=14.x

---

test/multipart.test.js

test: fix ci

---

app/extend/context.js

feat: use PassThrough instead of Writable
